### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by mbelang**
Changed the npmconf version to 2.0.1 since 2.1.1 doesn't exist on maven.

### CODE REVIEW

**Comment by nicks** [comment]
This exists fine for me:
```shell
$ npm info npmconf | grep 2.1.1
     '2.1.1',
     '2.1.1': '2014-10-07T21:38:28.552Z',
```

can you provide additional information or repro steps? Maybe you're using a private mirror that needs to be updated.

**Comment by mbelang** [comment]
When i'm looking in the pom.xml here : http://search.maven.org/#artifactdetails%7Corg.webjars.npm%7Cphantomjs%7C1.9.17%7Cjar

I see npmconf 2.1.1 which is not available on the maven repository. Only 2.0.1 is present as you can see here : http://mvnrepository.com/artifact/org.webjars.npm/npmconf. Now maybe I jumped into conclusion that the pom.xml was generated from the package.json.

I added phantomjs in my pom.xml and it complains about not finding npmconf 2.1.1 version which as I say not present in the maven repository. And yes i'm using a local repository which is configured as a mirror so when it doesn't contain a dependency it fetch it from global repository.

Either we downgrade to npmconf 2.0.1 or we upload 2.1.1 on maven. I don't mind but there is clearly a problem on maven.

**Comment by nicks** [comment]
yes, the maven repo is missing releases and should be fixed.

**Comment by mbelang** [comment]
Who should fix it? Where is the source of the maven builds?

**Comment by nicks** [comment]
i don't know enough about maven to be able to help you with this. I would probably start by contacting the owners of that maven repo?

**Pull request closed without merging**
