### PR TITLE
Fixed Issue #535, Trying to install phantomjs-prebuild@2.1.7 failed i…

### PR DESCRIPTION
**Pull request by vkkotha**
…nside docker,

### CODE REVIEW

**Comment by giorgiosironi** [comment]
I'm not inside Docker, but I have the same problem. This is a workaround but it's functionally equivalent to skipping the ones that are `undefined` as `/tmp` is checked twice.

**Comment by vkkotha** [comment]
If the environment returns any thing other than undefined like /c/temp etc... then the list won't have /tmp twice. having /tmp in the list won't hurt because, because the first valid path is chosen.

**Comment by Mauricio3000** [comment]
Had this issue on CentOS 7 Docker container.

My problem was that I was missing tar and bzip2

Once I installed them, no more errors.

I also exported TEMP & TEMPDIR as /tmp, but that didn't fix it until I installed tar and bzip2.

**Comment by nicks** [comment]
this change doesn't seem right...i handled this differently in #574

**Pull request closed without merging**
