### PR TITLE
reorganize phantomjs installer and add lint checks

### PR DESCRIPTION
**Pull request by nicks**
Hello @kylehg, 

Please review the following commits I made in branch 'nick-faster'.

a9743236550f12279f0a3913411807f8e5b7b9ee (2015-09-23 19:17:47 -0400)
reorganize phantomjs installer and add lint checks

R=@kylehg

MANUAL TESTING=not manually tested

### CODE REVIEW

**Comment by nicks** [comment]
there should be no functional changes here. I just moved everything into functions and reorganized

**Comment by nicks** [comment]
i also updated this to use travis-on-docker, which should be a bit faster. we should go through all our repos and do this
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

**Comment by kylehg** [comment]
lg

**Comment by nicks** [comment]
thanks for the review!

**Pull request merged**
