### PR TITLE
Add support for npm's cafile config directive for CA trust

### PR DESCRIPTION
**Pull request by deployable**
https://github.com/Medium/phantomjs/issues/293

### CODE REVIEW

**Comment by nicks** [comment]
this should be fixed in #296

**Comment by deployable** [comment]
https://github.com/Medium/phantomjs/pull/296 only deals with the `ca` config option. Mine was only `cafile`. I'll submit another pr merging the two.

**Comment by nicks** [comment]
@deployable I'm pretty sure npmconf does this internally. see https://github.com/npm/npmconf/blob/master/test/certfile.js

**Comment by deployable** [comment]
Nice. Thanks.

**Pull request closed without merging**
