### PR TITLE
Update Travis CI NodeJS versions matrix

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Comment by jzaefferer** [comment]
Testing on every minor release seems like a bad idea, since it'll just flow up the time to run tests. How about running on all latest major releases, e.g. 5.3, 4.2? Though 5.3 is already outdated, latest 5.x is 5.5.

**Comment by jzaefferer** [comment]
PS: Should set to `5` and `4` to test latest major releases. Like you did in https://github.com/gruntjs/grunt-lib-phantomjs/commit/9d8b958046d3b7467906057a6def9f348bf42ec4

**Comment by ntwb** [comment]
Ha, I've no idea why I added all the minor versions, will update the pull request shortly

**Comment by nicks** [comment]
lgtm

**Comment by nicks** [comment]
thanks!

**Pull request merged**
